version: '3'

services:
  # Uncomment when running dockerized
  # gateway:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ${PWD}/data/gateway/default.conf:/etc/nginx/conf.d/default.conf
  #     - ./certbot-etc:/etc/letsencrypt
  #     - ./certbot-var:/var/lib/letsencrypt
  #   depends_on:
  #     - sg-api
  #   networks:
  #     - sg-net

  # sg-api:
  #   image: wallscope/sg:0.0.1
  #   environment:
  #     - _JAVA_OPTIONS=-Xmx512m -Xms256m
  #     - TRIPLESTORE=http://sg-triplestore:3030/ds
  #     # - KC_ENABLED=true
  #     # - KEYCLOAK_SERVER_URL=http://keycloak:3003
  #     # - KEYCLOAK_CLIENT_SECRET=
  #   ports:
  #     - "2000:2000"
  #   volumes:
        # Make sure the path here is correct
  #     - "${PWD}/app/src/main/webapp/dist:/build/resources/main/static"
  #   depends_on:
  #     - sg-triplestore
  #   networks:
  #     - sg-net

  sg-triplestore:
    image: secoresearch/fuseki:4.6.1
    user: "9008:0"
    ports:
      - "2030:3030"
    environment:
      - ADMIN_PASSWORD=admin
    volumes:
      - ${PWD}/data/triplestore/data:/fuseki-base/databases
      - ${PWD}/data/triplestore:/fuseki-base/configuration
    restart: on-failure
    networks:
      - sg-net

networks:
  sg-net:
